name: "Setup flatc"
description: "Setup flatc for use in actions"
author: "Nugine"
inputs:
  version:
    description: "The version of flatc to install"
    required: true
runs:
  using: "node20"
  main: "dist/main.js"
