name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deno:
    runs-on: ubuntu-latest
    env:
      DENO_DIR: ""
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - uses: denoland/setup-deno@v2
      - run: echo "DENO_DIR=$HOME/.cache/deno" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          path: ${{ env.DENO_DIR }}
          key: deno-${{ hashFiles('deno.lock') }}
      - run: just ci

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          version: "24.3.25"

      - run: flatc --version
